### ISSUE TITLE
Output files for openmalaria.umbrella are lost

### ISSUE THREAD

**Issue by Baguage** [cooperative-computing-lab/cctools#1032] opened 2015-11-18 18:24 UTC
Trying to use the latest version of Umbrella to run OpenMalaria model, and do not get output files (ctsout.txt and output.txt) back.

**Comment by hmeng-19** [comment] 2015-11-18 19:42
@Baguage , Thanks for the report.

The reason for this problem is the output files are created inside a Docker container, and left behind after the job is done.

There are two solutions here: (1) save the whole Docker container into a tarball and find the output files from the tarball. (2) track output files using docker volumes.
The first solution is very expensive in both time and space consumption. I am currently working on a branch based on the second solution.

**Comment by Baguage** [comment] 2015-11-18 20:11
Out of curiosity, can you utilize `docker diff` command and grab only changed and added files in tarball? - http://docs.docker.com/engine/reference/commandline/diff/ (I'm not exactly sure how Umbrella builds an image and whether it is going to work or not though)

**Comment by dthain** [comment] 2015-11-18 20:16
Or (3) Umbrella copies the output files individually out of the container
and to the desired location.

**Comment by hmeng-19** [comment] 2015-11-20 20:30
@Baguage , `docker diff` gives you some overview of which files have been added, which files have been modified, or deleted. However, I do not think currently docker exposes some interface allowing you to subtract a single files from its storage space.

**Comment by hmeng-19** [comment] 2015-11-20 20:31
@dthain , the problem is when docker is used, umbrella can not copy files created inside a docker container except running as root.

**Comment by hmeng-19** [comment] 2015-11-20 20:49
@Baguage , would you like give this branch a try before I merge it into our ccl master?
https://github.com/hmeng-19/cctools/tree/umbrella_output

**Comment by hmeng-19** [comment] 2015-11-20 20:52
@Baguage , as for the latest version of `openmalaria.umbrella`, you can use the one under `cctools/umbrella/example/openmalaria`, or use the one in the ccl git repo we are collaborating one (I already pushed the latest version into it).

**Comment by Baguage** [comment] 2015-11-20 21:33
@hmeng-19 - thanks! I will try new version this Monday

**Comment by Baguage** [comment] 2015-11-23 01:37
Just tried it - got two output files back, so it sounds like it worked!

**Comment by hmeng-19** [comment] 2015-11-23 14:53
Cool. Thanks.

**Comment by hmeng-19** [comment] 2015-11-23 14:54
Fixed by #1043

**Closed by hmeng-19** 2015-11-23 14:54 UTC
Labels: Umbrella
