### ISSUE TITLE
Work Queue sending large file first

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1686] opened 2017-06-28 18:43 UTC
As reported to me via @Conman66, Work Queue was having trouble sending a large file as the initial file from Makeflow. 

Work Queue would report that the average transfer speed was 0.00 Mb/s and give 10 seconds to send the first file. The first file was >4GB and failed to send within the 10 sec limit and fail repeatedly.

This was resolved in the Makeflow by creating/sending a small file initially, though there should be better method to avoid this.

**Comment by btovar** [comment] 2017-06-28 22:51
Given the wq defaults, those 10 seconds should be instead close to 1h. Checking what's broken...

**Comment by btovar** [comment] 2017-06-28 23:44
Something else is going on.  In a small test, sending just a single 4GB file, I get: 38146s to wait, which roughly corresponds to 3600 seconds  * acceptable factor of 10, with the conservative default.

@Conman66, please try running your makeflow master in another machine. @nkremerh, please help him do that tomorrow.

**Comment by btovar** [comment] 2017-06-28 23:53
@Conman66, you can also run the following example:

On helix, create the following file small.py:

```
#! /usr/bin/env python

from work_queue import *
cctools_debug_flags_set('all')
q = WorkQueue(0)
q.specify_name('small_example')

t = Task('/bin/echo hello')
t.specify_input_file('inputfile')

q.submit(t)
t = q.wait(60)
```
create the inpufile:
dd  bs=1GB count=4 if=/dev/zero of=inputfile

run the master:
python small.py

On a disc machine:
work_queue_worker -dall -M small_example

If that works, then the problem is with how the workflow is setup. If it does not, then the problem may be with helix.

@nkremerh, please supervise as necessary.

**Comment by btovar** [comment] 2017-06-30 11:08
@nkremerh Any updates?

**Comment by btovar** [comment] 2017-07-31 16:52
Closing as we cannot reproduce it.

**Closed by btovar** 2017-07-31 16:52 UTC
Labels: bug, Work Queue
