### ISSUE TITLE
Reading work_queue_task.hostname gives foreman's machine instead of task's machine

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#682] opened 2015-03-11 19:36 UTC
Accessing [work_queue_task.hostname](https://github.com/cooperative-computing-lab/cctools/blob/master/work_queue/src/work_queue.h#L78) through the python API is returning the hostname of the foreman which is running the task. Is this expected? From a user perspective, it would be preferable to have access to both pieces of information: the task host and foreman host.

**Comment by batrick** [comment] 2015-04-09 15:28
@nhazekam please check this out.

**Comment by nhazekam** [comment] 2015-04-09 17:33
I can confirm that this is indeed the case and is the expected behavior. This is due to interactions between master->foreman->worker, where the master for most cases assumes the foreman is a simple worker and does the work, so in the master's record the task's hostname is that of the foreman. Though this is the expected behavior, we will discuss if there is any other means of getting the information about the actual execution site. @btovar @dthain

**Comment by dthain** [comment] 2015-04-10 16:51
As we discussed today, please start a new ticket to discuss/address problems related to the interaction of the foreman with all aspects of WQ, and then let's work backward from that to see if there is a short-term solution to Anna's problem.

**Comment by nhazekam** [comment] 2015-05-11 14:41
This is currently being discussed/addressed with #706. Please refers comments to that thread.

**Comment by dthain** [comment] 2015-10-05 20:22
Merged with #706

**Closed by dthain** 2015-10-05 20:22 UTC
Labels: question, Work Queue
