### ISSUE TITLE
WQ factory condor Disk requirement issue

### ISSUE THREAD

**Issue by khurtado** [cooperative-computing-lab/cctools#1718] opened 2017-08-07 18:51 UTC
Hello,

When using condor_submit_workers or work_queue_factory with condor, the condor Arguments set by these look like:
 
Arguments = "./work_queue_worker -M lobster_khurtado_mc_v1 -t 300 -C ''''catalog.cse.nd.edu,backup-catalog.cse.nd.edu:9097'''' --cores=$$([TARGET.Cpus]) --memory=$$([TARGET.Memory]) --disk=$$([TARGET.Disk/1024])"

So, the disk is set to the maximum disk advertised in the target. The problems I am seeing is when these workers are running inside condor glideins / user-launched startds.

-) If these glideins start in a shared-filesystem (let's say `/gpfs/shared1`), condor will advertise the free disk space available in such directory, but the worker will try to use `/tmp` by default. If the disk space available in `/tmp` is less than the available in the shared filesystem, the worker will terminate itself complaining with a message like:

``` 
work_queue_factory -T condor -M "task" -C workers.conf
work_queue_worker: has less than the promised disk space (--disk > disk total) 
```
To solve that issue I am using the workdir extra option, so that it uses the same directory the glidein is starting the condor startd to: ``` --extra-options="--workdir=./```

However,  if the free space in the FS is decreasing at the moment, the worker still will fail, the startd updates the TARGET.Disk value and eventually the worker gets to run.

So, right now I am submitting my worker to condor manually requesting 95% of the promised space, to be more conservative ```--disk=$$([TARGET.Disk * 95/ 102400])```

Is there any way to do this more properly using work_queue_factory / condor_submit_workers ?

**Comment by btovar** [comment] 2017-08-07 19:38
Why aren't your workers running on the shared filesystem? They should only use /tmp if none of _CONDOR_SCRATCH_DIR, or TMPDIR are set.   

(If this is vc3, are you using the vc3-builder? If so, try adding to the builder command line --revar _CONDOR_SCRATCH_DIR, to preserve its value inside the builder).

If for some reason the worker cannot run in the scratch dir condor created for the job, then probably there is no better way. You could use --disk=all but it would have the same problems as your current solution ( /tmp is not only writable by that particular worker).

The problem is that the worker has to trust that the node will respect the given resources. Using TARGET.Disk takes care of that. Making the worker run somewhere else breaks that contract.

**Comment by khurtado** [comment] 2017-08-07 20:30
Yep, it's running through the builder. Adding `--revar TMPDIR ` works, I can now get rid of `--extra-options="--workdir=./`, thanks!

I still have the second issue though (workers running but finding out current free space in the FS scratch dir is now  some MBs smaller than what Target.Disk advertised to begin with). In case of the  WQ factory, more workers are simply submitted until they eventually are happy and run though, but it is kind of annoying and I'm not really sure how to improve that without modifying the `--disk` option.

**Comment by btovar** [comment] 2017-08-08 12:27
Is TARGET.Disk advertising the whole shared filesystem? If so, that seems to quickly lead to trouble, as disk space will be over-committed.  You would have to specify --disk=X where X is some absolute value (that is, not a fraction of TARGET.Disk).

**Comment by khurtado** [comment] 2017-08-08 14:21
I think condor basically advertises what `df -kP /path` does, so yes.

> You would have to specify --disk=X where X is some absolute value (that is, not a fraction of TARGET.Disk)

Yeah, at first, I just used `--disk=MY.RequestDisk/1024`. My point is, whatever value I choose (absolute or some fraction of TARGET.Disk), I can only do it by creating my own condor submit files, not directly with condor_submit_workers or the WQ factory, as these two always use `--disk = TARGET.Disk/1024`, which is inconvenient for this particular case.

**Comment by btovar** [comment] 2017-08-08 14:39
Why do you need to create your own submit files? Can't you use the --disk option for the factory and condor_submit_files?

**Comment by khurtado** [comment] 2017-08-08 14:50
Not really, `--disk` sets `request_disk` in the condor submit file to the right value, but the argument for the work_queue_worker is always `--disk=$$([TARGET.Disk/1024])"`, no matter what I put on the work_que_factory`--disk` option.

**Comment by btovar** [comment] 2017-08-08 14:53
Ah, got it.

In the meantime, I would suggest copying condor_submit_workers to condor_submit_workers_vc3 where you can set --disk=all

**Comment by khurtado** [comment] 2017-08-08 15:02
Good idea! Will do that.

**Comment by btovar** [comment] 2017-08-08 15:05
This issue you brought up really breaks some of the assumptions we have been making with regards to TARGET.disk. I wonder how sites deal with the over-commitment of disk...

**Comment by dthain** [comment] 2017-08-14 18:52
The fundamental problem here is that our underlying systems don't support the notion of "allocation".  As a result, the reported "available" space is meaningless, because you can't differentiate between space that is "claimed but unused" and space that is "unallocated for any purpose".    As a result, *no* site deals with this in any satisfactory way...

**Comment by btovar** [comment] 2017-09-26 16:18
Closing, as there is not a general way to fix this.

**Closed by btovar** 2017-09-26 16:18 UTC
