### ISSUE TITLE
vine: add debug log to libtask, return on failure

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3806] opened 2024-05-02 12:35 UTC
I had trouble debugging library tasks. The python code was generating an exception and I had to manually redirect stderr to a file in `/tmp`. It would be very useful if on failure, the library task returns its standard output and error. Maybe related to what @BarrySlyDelgado is currently doing returning stdouts.

**Comment by dthain** [comment] 2024-05-17 14:54
Closing as duplicate of #3570

**Closed by dthain** 2024-05-17 14:54 UTC
Labels: enhancement, TaskVine
