### ISSUE TITLE
vine: workers without peer transfers and temp files

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3830] opened 2024-05-09 19:37 UTC
If a worker does not have a transfer port, should it be able to execute tasks with temporary files?  In general I'd say no, but maybe there are cases where a single large worker is executing the workflow?

One possible issue right now is that a temp file may be recreated at many workers because the worker can't fetch it from each other (if I understood the code correctly).

**Comment by dthain** [comment] 2024-05-09 19:44
Hmm, under what conditions would the worker not have a port at all?  Are you observing cases where listening on the port fails, or is this a situation where the user deliberately disables the transfer port?

**Comment by btovar** [comment] 2024-05-09 20:59
Once in a while condor+docker give me a worker whose reported port can't be accessed by other workers.

**Comment by btovar** [comment] 2024-05-09 21:00
Once in a while meaning one or two in 1000 workers, but enough to halt a workflow.

**Comment by dthain** [comment] 2024-09-27 18:00
Duplicate of #3763

**Closed by dthain** 2024-09-27 18:00 UTC
Labels: enhancement, TaskVine
