### ISSUE TITLE
Idea: add crash/statistics reporting to CCTools

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#1167] opened 2016-02-23 14:44 UTC
A common problem we have is that Parrot "broke" but the user does not know how (easy it is) to report the problem or what we need to address the issue. A useful addition to CCTools would be crash and/or statistics reporting. This could allow us to easily gather:
- stack backtraces on aborts
- last lines of the debug log on failure
- system calls made by Parrot (or other tool specific data)
- cvmfs cache size / number of objects in cache
- forks  and clones made / max number of processes / Is the application using threading?
- number of file descriptors in use

A core question that must be answered first though is (a) when do we send reports and (b) how does the user turn them on (opt-in only!).

Probably (a) is on exit. (b) is the tricky part. Probably the default is don't send anything and we would have a configure flag to change the default to "on" . There would be a few command line switches to turn it on/off. The default might be to ask (if there is a controlling terminal) the user if they want to submit a bug report. Otherwise drop the report in $PWD and let the user decide what to do.

Please comment here with ideas or concerns.

**Comment by annawoodard** [comment] 2016-03-04 19:30
As a user, I think this is a fantastic idea. I agree that (a) should be on exit and that (b) should be to default to not sending anything and support configuration flags/command line switches to turn it on. My reason for wanting a way to enable it when there isn't a controlling terminal to ask if I want to submit a bug report is because my most common scenario is running into issues on the worker when running WQ + Parrot, and they aren't always straightforward to reproduce locally.

**Comment by annawoodard** [comment] 2016-03-04 19:33
Of course, going that route, there will always be the danger that the user misconfigures their script and spams you with thousands of bug reports...

**Comment by dthain** [comment] 2024-06-12 15:18
Closing out old but good ideas that didn't make it into the funnel.

**Closed by dthain** 2024-06-12 15:18 UTC
Labels: enhancement, Parrot
