### ISSUE TITLE
Work Queue worker does not work with Makeflow 

### ISSUE THREAD

**Issue by charleszheng44** [cooperative-computing-lab/cctools#863] opened 2015-07-20 02:53 UTC
After update the master branch. Makeflow and Work Queue keep hanging when running Makeflow command

~~~shell
makeflow -T wq
~~~

with Work Queue command

~~~shell
work_queue_worker localhost 9123
~~~

And the debug message is 

~~~shell
wq: couldn't link cache/file into sandbox as t.1/: No such file or directory 
~~~

The Makeflow file I used is the example Makeflow file from the Makeflow user manual.

**Comment by btovar** [comment] 2015-07-20 11:10
I cannot reproduce this with the master branch. Since you say 'after update', are you sure this problem is not with one of your local branches?

**Comment by btovar** [comment] 2015-07-20 11:39
Uhm, definitely not a problem in master. Closing.

**Closed by btovar** 2015-07-20 11:39 UTC
