### ISSUE TITLE
cctools-monitor does not properly wait for child processes to return before itself exiting

### ISSUE THREAD

**Issue by David-Simonetti-ND** [cooperative-computing-lab/cctools#2820] opened 2022-02-11 16:14 UTC
<img width="1432" alt="Screen Shot 2022-02-11 at 9 58 10 AM" src="https://user-images.githubusercontent.com/31227025/153627267-466d7932-ed3a-47e8-bfb5-1792aaf423ad.png">
The image is pictured above. The cctools-monitor process spawns a shell process that executes a python program on fn_wrapper, but in certain cases the cctools-monitor does not wait for child shell process and its python child process to return before exiting.

**Comment by dthain** [comment] 2022-02-11 16:47
@btovar does the resource monitor use the `process` module to detect completion, or something else?  (Trying to decide if this is a duplicate of #2819 )

**Comment by btovar** [comment] 2022-02-11 16:59
It does not. We do send a sigterm, wait at most 5s, and then send a sigkill for all the processes that we know, so this is interesting.

**Comment by dthain** [comment] 2022-05-18 15:45
@btovar is this fixed?

**Comment by btovar** [comment] 2022-05-18 15:50
Fixed #2821

**Closed by btovar** 2022-05-18 15:50 UTC
