### ISSUE TITLE
parrot and icecube segfault on RHEL6.8

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1548] opened 2016-11-22 14:06 UTC
From Gonzalo Merino:

We run opencl applications in a distributed environment. We rely in CVMFS for software distribution. In some sites, we do not have CVMFS native installations, therefore we rely on parrot (thanks a lot parrot developers!)

We are experiencing a weird issue with parrot at one of our sites, so I am writing this group to see if someone more expert than me in the internals can help us. This is what we observe:

There is one site where we are trying to run where trying to run the "clinfo" opencl binary via parrot crashes with segmentation fault. This is what we do:

# cat run-parrot
export PARROT_CVMFS_REPO="<default-repositories>"
export PARROT_ALLOW_SWITCHING_CVMFS_REPOSITORIES=yes
export HTTP_PROXY='INVALID-PROXY'
parrot_run /bin/bash

# ./run-parrot
# /cvmfs/icecube.opensciencegrid.org/distrib/OpenCL_Linux/bin/x86_64/clinfo
Segmentation fault

We are using parrot in cctools-6.0.10-x86_64-redhat6, and the OS in this site is RHEL 6.8

The node in which we are doing this has also native CVMFS installed (using fuse).
If we run the same  /cvmfs/icecube.opensciencegrid.org/distrib/OpenCL_Linux/bin/x86_64/clinfo command using the native CVMFS, the command runs just fine.

We are running this in several other RHEL6 or RHEL7 sites, where we can run this clinfo binary and other opencl applications inside parrot with no issues. There seems to be some problem with this specific RHEL 6.8 site.

Running parrot with "debug all" flag provides a lot of information, but I confess I am not able to get a clear idea of what is causing the problem from this debug dump. I have put the complete debug output in here in case someone in this group can help us with this:

http://icecube.wisc.edu/~gmerino/parrot/parrot.log.err

thanks a lot,
Gonzalo

2016/11/17 06:32:55.00 parrot_run[144781] process: pid 144945 received signal 11 (Segmentation fault) (state 1)
2016/11/17 06:32:55.00 parrot_run[144781] process: pid 144945 faulted on address 0x3038 (unmapped)
2016/11/17 06:32:55.00 parrot_run[144781] debug: 144945 maps:
00007fe1e79eb000-00007fe1e79f5000 rw-p            45000 08:03 30783532 /usr/lib64/libnvidia-fatbinaryloader.so.361.93.03
00007fe1e77a6000-00007fe1e79f5328 r-wp                0 08:03 30783532 /usr/lib64/libnvidia-fatbinaryloader.so.361.93.03
00000036c5e06000-00000036c5e08000 rw-p             6000 08:03 14131310 /lib64/librt-2.12.so
00000036c5c00000-00000036c5e07bb0 r-wp                0 08:03 14131310 /lib64/librt-2.12.so
00007fe1e831e000-00007fe1e843e000 rw-p           70d000 08:03 30783415 /usr/lib64/libnvidia-opencl.so.361.93.03
00007fe1e7a11000-00007fe1e8449b88 r-wp                0 08:03 30783415 /usr/lib64/libnvidia-opencl.so.361.93.03
00000036c4b8a000-00000036c4b90000 rw-p           18a000 08:03 14131224 /lib64/libc-2.12.so
00000036c4800000-00000036c4b93928 r-wp                0 08:03 14131224 /lib64/libc-2.12.so
00000036cea15000-00000036cea16000 rw-p            15000 08:03 14131240 /lib64/libgcc_s-4.4.7-20120601.so.1
00000036ce800000-00000036cea15d58 r-wp                0 08:03 14131240 /lib64/libgcc_s-4.4.7-20120601.so.1
00000036c4e02000-00000036c4e04000 rw-p             2000 08:03 14131283 /lib64/libdl-2.12.so
00000036c4c00000-00000036c4e03100 r-wp                0 08:03 14131283 /lib64/libdl-2.12.so
00000036c5282000-00000036c5284000 rw-p            82000 08:03 14131225 /lib64/libm-2.12.so
00000036c5000000-00000036c52830b8 r-wp                0 08:03 14131225 /lib64/libm-2.12.so
00000036c5617000-00000036c5619000 rw-p            17000 08:03 14131246 /lib64/libpthread-2.12.so
00000036c5400000-00000036c561c3f0 r-wp                0 08:03 14131246 /lib64/libpthread-2.12.so
00007fe1e866e000-00007fe1e866f000 rw-p             5000 08:03 30783442 /usr/lib64/libOpenCL.so.1.0.0
00007fe1e8469000-00007fe1e866eff0 r-wp                0 08:03 30783442 /usr/lib64/libOpenCL.so.1.0.0
0000000000400000-0000000000465000 r-xp                0 08:03 1902350404 /tmp/xs-gmerino/parrot.1000118/b5/b5e90992060ff4444d82317f4df78ae8
0000000000665000-000000000066a000 rw-p            65000 08:03 1902350404 /tmp/xs-gmerino/parrot.1000118/b5/b5e90992060ff4444d82317f4df78ae8
000000000066a000-000000000067c000 rw-p                0 00:00        0
000000000263f000-0000000002660000 rw-p                0 00:00        0 [heap]
00000036c4400000-00000036c4420000 r-xp                0 08:03 336794119 /lib64/ld-2.12.so
00000036c461f000-00000036c4621000 r--p            1f000 08:03 336794119 /lib64/ld-2.12.so
00000036c4621000-00000036c4622000 rw-p            21000 08:03 336794119 /lib64/ld-2.12.so
00000036c4622000-00000036c4623000 rw-p                0 00:00        0
00000036c4b90000-00000036c4b94000 rw-p                0 00:00        0
00000036c5619000-00000036c561d000 rw-p                0 00:00        0
00007fe1e7785000-00007fe1e77a6000 rw-p                0 00:00        0
00007fe1e79f5000-00007fe1e79f6000 rw-p                0 00:00        0
00007fe1e7a10000-00007fe1e7a11000 r--s         d0000000 00:05    99105 /dev/nvidia1
00007fe1e843e000-00007fe1e844e000 rw-p                0 00:00        0
00007fe1e8459000-00007fe1e8469000 rw-p                0 00:00        0
00007fe1e866f000-00007fe1e8671000 rw-p                0 00:00        0
00007ffdf4310000-00007ffdf4326000 rw-p                0 00:00        0 [stack]
00007ffdf4375000-00007ffdf4376000 r-xp                0 00:00        0 [vdso]
ffffffffff600000-ffffffffff601000 r-xp                0 00:00        0 [vsyscall]

**Comment by dthain** [comment] 2016-11-22 16:04
Observation: clinfo is faulting on a `ioctl` syscall.  The current parrot generally passes through ioctls on non-regular files.  However, it seems to think that the address is `0x3038` which should never be a regular user space address.  (It looks more like an ioctl code, in fact.)

```
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> syscall: ioctl
2016/11/17 06:32:55.00 parrot_run[144781] <child:144945> syscall: = 0 [ioctl]
2016/11/17 06:32:55.00 parrot_run[144781] process: pid 144945 received signal 11 (Segmentation fault) (state 1)
2016/11/17 06:32:55.00 parrot_run[144781] process: pid 144945 faulted on address 0x3038 (unmapped)
```

**Comment by dthain** [comment] 2016-11-22 16:05
@trshaffer are you able to reproduce this one?

**Comment by batrick** [comment] 2016-11-29 01:02
I noticed this in the log right before the segfault:

````
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> syscall: stat
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> libcall: stat /proc/144945/ns/pid 0x7ffde0d667a0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> resolve: /proc/144945/ns/pid = /proc/144945/ns/pid,0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: readlink /proc/144945/ns/pid 0x7ffde0d639a0 1023
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: = 16 [readlink]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> resolve: /proc/144945/ns/pid:[4026531836] = /proc/144945/ns/pid:[4026531836],0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: readlink /proc/144945/ns/pid:[4026531836] 0x7ffde0d60cb0 1023
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: = -1 No such file or directory [readlink]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: stat /proc/144945/ns/pid:[4026531836] 0x7ffde0d667a0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: = -1 No such file or directory [stat]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> libcall: = -1 No such file or directory [pfs_stat]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> syscall: = -2 No such file or directory [stat]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> syscall: stat
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> libcall: stat /proc/144945/ns/pid 0x7ffde0d667a0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> resolve: /proc/144945/ns/pid = /proc/144945/ns/pid,0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: readlink /proc/144945/ns/pid 0x7ffde0d639a0 1023
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: = 16 [readlink]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> resolve: /proc/144945/ns/pid:[4026531836] = /proc/144945/ns/pid:[4026531836],0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: readlink /proc/144945/ns/pid:[4026531836] 0x7ffde0d60cb0 1023
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: = -1 No such file or directory [readlink]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: stat /proc/144945/ns/pid:[4026531836] 0x7ffde0d667a0
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> local: = -1 No such file or directory [stat]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> libcall: = -1 No such file or directory [pfs_stat]
2016/11/17 06:32:54.98 parrot_run[144781] <child:144945> syscall: = -2 No such file or directory [stat]
````

That `stat` failure may have led to the code path which segfaulted. Maybe fixing that will be a workaround.

**Comment by trshaffer** [comment] 2016-11-30 18:27
I `straced` the same program to find differences from Parrot's behavior just before the segfault. Digging around with GDB, I reproduced @batrick's suggested cause, but that didn't do it. Shortly after that `stat` call, the program tries to set up a socket, and Parrot does the wrong thing there. The syscall should succeed, but Parrot returns `ENOENT`. If I manually reproduce Parrot's behavior, the segfault indeed happens, so I'm pretty confident this is the cause.

The issue on Parrot's end is in handling of `AF_UNIX` sockets. The program was trying to bind an abstract socket (the name is prefixed with a null byte). Parrot thinks this is just a zero-length string, and fails. @dthain, since abstract socket names have no connection with file system pathnames, can we just let this syscall fall through like the other address families?

**Comment by dthain** [comment] 2016-11-30 18:31
@trshaffer I'm not intimately familiar with abstract sockets, so I can't say.  You should read up on the concept, and then give us your professional opinion.  Happy to work through it on the whiteboard if you like.

**Comment by trshaffer** [comment] 2016-11-30 18:35
Abstract sockets are `AF_UNIX`, but bind to an arbitrary string rather than a filesystem path. Parrot currently lets other socket types, e.g. `AF_INET`, fall through, and I'm inclined to do the same for abstract sockets. I'll verify that this approach fixes the issue, then put in a pull request

**Comment by batrick** [comment] 2016-11-30 20:42
I would suggest opening another issue for the broken stat of `/proc/*/ns/...`. That should be fixed too.

**Comment by dthain** [comment] 2016-12-01 14:58
Tim, if this is ready to go, please respond to Gonzalo and see if he is satisfied.

**Closed** 2016-12-06 16:19 UTC
Labels: bug, cvmfs, Parrot
