### ISSUE TITLE
Vine: Let Library execute arbitrary cloudpickled functions

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3320] opened 2023-05-04 21:48 UTC
Currently the python coprocess executes functions that it know about by the name of the function. Thus, if new functions are created a the manager dynamically, they cannot be used be used by current coprocesses. In dask, the task graph calls functions by using wrappers to the original functions, thus their definitions/names do not exists in the coprocesses library. However, the cloudpickled version of this wrapper function is easily executed via PythonTask.  Many dask functions run for less than a second, thus the overhead of relaunching the interpreter is very noticeable. It would be very helpful if in addition to refering to the function by name, we could use its cloudpickled representation.

**Comment by dthain** [comment] 2023-05-05 13:01
Name it by hash of the pickle content?
Or would that be too large?

**Comment by benclifford** [comment] 2023-10-05 06:49
This is something relevant to parsl vs taskvine too, I think - and is something that the TaskVine Parsl executor deals with, right?

**Comment by tphung3** [comment] 2023-10-05 17:50
Currently for dynamically generated (e.g., lambda, eval()) or wrapper-modified functions are not natively supported by TaskVine, as it defines a `Library` as a static set of source-code functions. For now the executor code handles these kinds of functions through a special helper function.

For example, let say we want to run function `f` (wrapped or not, dynamic or not) with argument list `A`. The executor cloudpickles `f` and `A` to two files, `function` and `arguments`. The special helper function then takes these two files, deserializes them, and executes, like this:
```
def special_function(function_fn, arguments_fn):
    func = cloudpickle.load(function_fn)
    args = cloudpickle.load(arguments_fn)
    # update func with fn_name to global() namespace
    return global()[fn_name](args)
```

This is a bandage solution of course, as a function must be loaded from a file everytime (1 file load per invocation). In the future, functions will be ID'ed and registered to the library process to get 1 file load per many invocs.

**Comment by tphung3** [comment] 2023-10-05 17:52
@btovar I think you can write the special function for Dask for now. Per addressing by cloudpickled representation, in the future I think functions are cacheable objects so we can identify them by checksumming the cloudpickled file (native to TaskVine).

**Comment by btovar** [comment] 2023-10-05 17:56
Sounds good! So the only thing I need to do is to construct a library that has that `special_function`?

**Comment by btovar** [comment] 2023-10-05 18:01
Thanks, nice job!

**Comment by dthain** [comment] 2023-10-05 18:07
@tphung3 is there anything stopping us from making a variant of `PythonTask` or `LibraryTask` that accepts a cloud pickle natively?

**Comment by tphung3** [comment] 2023-10-05 18:14
@dthain No, this feature could also be included when the library is reimplemented to accept and register non-source-code functions.

**Comment by dthain** [comment] 2024-06-11 18:44
Duplicate of #3405

**Closed by dthain** 2024-06-11 18:44 UTC
