### ISSUE TITLE
vine: tasks that use temp files may fail if peer transfers are not enabled

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3218] opened 2023-03-20 19:03 UTC
@colinthomas-z80, you probably already know about this one. If a task depends on a temp file and the file is not at the worker, the task fails if peer transfers are not enabled.

Here are some ideas:

- Always transfer back temp files if peer transfers are not enabled.
- Do not dispatch tasks to workers if temp files are needed and peer transfers are not enabled. Terminate with an error.
- Do not allow temp files as inputs unless the strict input flag is added to the mount.

**Comment by dthain** [comment] 2023-08-16 16:03
Duplicate of #3281

**Closed by dthain** 2023-08-16 16:03 UTC
Labels: bug, TaskVine
