### ISSUE TITLE
parrot and flock bug

### ISSUE THREAD

**Issue by khurtado** [cooperative-computing-lab/cctools#1875] opened 2018-03-01 06:00 UTC
Hi,

I am running a condor glidein that requires cvmfs via parrot. This works fine if I run it interactively, but if I execute it through condor, it hangs when condor_cron makes a  `flock` waiting for a specific file descriptor at some point.

Isolating this case is hard, but I could provide a way to run the whole glidein from earth if that helps.

In the meantime, what I see is the condor executes a script called `script_wrapper.sh`, which calls `flock` and waits for fd 200.
```
bash-4.1$ pstree -alcp khurtado
condor_exec.exe,21322 /var/condor/execute/dir_21318/condor_exec.exe 0 1418097
  └─nosingu_glidein,21377 ./nosingu_glidein_d12chas.sh
      └─parrot_cvmfs_st,21378 -d all -o /scratch365/khurtado/myglidein_test4/parrot301_t3_d12chas_dot_21358.debug -M/cvmfs/cms.cern.ch/SITECONF/local=/scratch365/khurtado/myglidein_te
          └─6,21379 ./run_glidein3.sh
             └─19,21380 ./glidein_startup.sh -v std -name gfactory_instance -entry CMSHTPC_T3_US_NotreDame_deepthought -clientname CMSG-v1_0.main -schedd schedd_glideins2@gfactory-1.t2.ucsd.edu
                 └─34,2360 /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/condor_startup.sh glidein_config
                     └─37,3327 -f -pidfile /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/condor_master2.pid
                         ├─68,3331 -A /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/log/procd_address -L /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/log/ProcLog -R 1000000 -S 60 -C 211834
                         └─76,3332 -f
                             ├─77,3451 /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/script_wrapper.sh glidein_config main GLIDEIN_PS_1/scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/check_wn_
                             │   └─77,3632 /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/script_wrapper.sh glidein_config main GLIDEIN_PS_1/scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/check_wn_
                             │       └─81,3640 /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/glidein_config /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/glidein_config.old
                             ├─78,3453 /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/script_wrapper.sh glidein_config main GLIDEIN_PS_2/scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/mjf_setpa
                             │   └─78,3638 /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/script_wrapper.sh glidein_config main GLIDEIN_PS_2/scratch365/khurtado/myglidein_test4/glide_eIL2Qz/main/mjf_setpa
                             │       └─81,3639 -w 300 -e 200
                             └─80,3479
```
The flock process goes into `T` state.
```
khurtado  3639  0.0  0.0   4056   472 ?        T    00:38   0:00 flock -w 300 -e 200
```
And I can see 200 has been deleted
```
bash-4.1$ pwd
/proc/3639/fd
bash-4.1$ ls -l
total 0
l-wx------ 1 khurtado campus 64 Mar  1 00:46 1 -> pipe:[626499920]
l-wx------ 1 khurtado campus 64 Mar  1 00:46 2 -> pipe:[626499921]
l-wx------ 1 khurtado campus 64 Mar  1 00:46 200 -> /var/condor/execute/dir_21318/parrot.211834/parrot-instance.soG6qM/parrot-fd.R6gZum/pfs@-scratch36...in_config.lock (deleted)
lr-x------ 1 khurtado campus 64 Mar  1 00:46 4094 -> /var/condor/execute/dir_21318/parrot.211834/parrot-instance.soG6qM/parrot-fd.R6gZum
lrwx------ 1 khurtado campus 64 Mar  1 00:46 4095 -> /dev/shm/parrot-channel.KkAhOP (deleted)
```

Using readlink on `200` seems weird though, the full path isn't shown, there are some dots `...`, as if the path was too long or something.

```
bash-4.1$ readlink 200
/var/condor/execute/dir_21318/parrot.211834/parrot-instance.soG6qM/parrot-fd.R6gZum/pfs@-scratch36...in_config.lock (deleted)
```

This is me after doing `condor_ssh_to_job` into the machine though, I'm not sure if looking at `/proc/3639/fd` from the parrot instance would look any different.

EDIT: These are the last lines of parrot in debug mode
````
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/usr)
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/usr/lib)
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/usr/lib/libacl.so.1)
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> libcall: = -1 No such file or directory [pfs_open]
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] process: waiting for blocking event from process 3640
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> syscall: = -2 No such file or directory [open]
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3639> syscall: = 0 [setitimer]
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> syscall: open
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> libcall: open tls/x86_64/libacl.so.1 0 0
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> resolve: /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/tmp.w1GRtoCNJw/tls/x86_64/libacl.so.1 = /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/tmp.w1GRtoCNJw/tls/x86_64/libacl.so.1,5
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> local: readlink /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/tmp.w1GRtoCNJw/tls/x86_64/libacl.so.1 0x7fffe41e61c0 1023
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> local: = -1 No such file or directory [readlink]
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> local: open /scratch365/khurtado/myglidein_test4/glide_eIL2Qz/tmp.w1GRtoCNJw/tls/x86_64/libacl.so.1 2048 0
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> local: = 2 No such file or directory [open]
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> libcall: = -1 No such file or directory [pfs_open]
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] process: waiting for blocking event from process 3640
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3640> syscall: = -2 No such file or directory [open]
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3639> syscall: flock
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3639> libcall: flock 200 2
2018/03/01 00:38:57.12 parrot_cvmfs_static_run[21378] <child:3639> local: flock 77 2
```
Any ideas ?

**Comment by btovar** [comment] 2018-03-01 12:24
Kenyi, where are you trying this? I am able to launch in the vc3 ND allocation:

(builder with parrot-cvmfs) -> vc3-glidein -> condor

**Comment by khurtado** [comment] 2018-03-01 12:51
Hi Ben,

I am able to do the same with the vc3-glidein, the one I'm having issues with is the CMS glidein, which executes a bunch of scripts before the actual payload, and updates a bunch of stuff via condor_cron.

**Comment by btovar** [comment] 2018-03-01 12:54
Can we execute it semi-locally to ease debugging? For example, launch an interactive condor node and then run the CMS glidein manually?

**Comment by khurtado** [comment] 2018-03-01 14:03
Yes, that can be done. Parrot works fine if executed on the worker node interactively, but somehow still fails if executed interactively under a condorSSH session. Let me set things up to send instructions on what to run.

**Comment by khurtado** [comment] 2018-03-07 18:36
Hello @btovar @trshaffer 

Here is a simplified case. If I have some flock function [1] and execute it through a wrapper [2] more than once, bash will print something like below, but running it through parrot hangs in the flock part forever.

```
Hello PS
Hello1 Greeting glidein
Hello2 Greeting glidein
```
[1]
```
#! /bin/bash
# flock.sh
glidein_config=$PWD/glidein_config

function add_config_line_safe {
    grep -q "^${*}$" $glidein_config
    if [ $? -ne 0 ]; then
        # when fd is closed the lock is released, no need to trap and remove the file
        (
        flock -w 300 -e 200 || (echo "Error acquiring lock for glidein_config"; exit 1)
        echo "Sub-shell: BASHPID: $BASHPID"
        add_config_line_unsafe "$@"
        sleep 5
        ) 200>${glidein_config}.lock
    fi
}

function add_config_line_unsafe {
    echo "$@" >> $glidein_config
    #sleep 5
}
```

[2]
```
#! /bin/bash

source $PWD/flock.sh

if [ -f glidein_config.lock ]; then rm glidein_config.lock; fi
echo "Hello PS" > glidein_config

add_config_line_safe "Hello1" "Greeting" "glidein" &
add_config_line_safe "Hello2" "Greeting" "glidein" &
```

**Comment by trshaffer** [comment] 2018-03-09 21:22
I haven't been able to reproduce this, but it looks like Parrot's `flock` support is broken. When run on the command line, the `flock` program does the following.
1. Schedule a `SIGALRM` after the timeout specified on the command line.
2. Call `flock(2)`.
3. If woken up by the signal, exit failure.

Parrot doesn't handle `flock(2)` correctly, though. For native FDs, things would work fine as the `flock()` call would be passed through unmodified. If Parrot is virtualizing the file descriptor, it calls `flock()` itself, i.e. from within the Parrot process. This blocks Parrot until the lock is released. The signal scheduled by the command line `flock` program is delivered to the child programs, but if Parrot itself is blocked, the alarm signals will never reach them. If two programs running under Parrot try to synchronize through `flock`, it's likely to deadlock the entire Parrot instance. This is incorrect, but Parrot's file descriptor handling makes it difficult to properly handle `flock(2)`.

In the mean time, I put in a PR that adds a flag to disable `flock(2)`. This *might* get your glidein working. As long as your appends aren't too long they'll be atomic anyway, so you might be OK while we sort this out.

CC @dthain

**Comment by khurtado** [comment] 2018-03-09 23:55
@trshaffer Thanks! Will try it. @btovar, could you do the static compilation with that PR to test?

**Comment by khurtado** [comment] 2018-04-06 19:42
So, this is working! @btovar: Is there a version of cctools with this change integrated already? I would like to update the builder cctools recipe.

**Comment by btovar** [comment] 2018-04-09 11:38
It has not been merged yet. I will do that shortly.

**Closed by btovar** 2018-04-09 11:38 UTC

**Comment by btovar** [comment] 2018-04-09 16:57
@khurtado: the builder has been updated accordingly. (--require cctools)

**Comment by khurtado** [comment] 2018-04-09 16:58
@btovar Great! Thanks!

**Comment by khurtado** [comment] 2018-04-09 19:18
@btovar Just do double check, `6.2.10` PR #1860 , #1837 and #1851, correct?

**Comment by btovar** [comment] 2018-04-10 11:15
Yes, they are included.
