### ISSUE TITLE
parrot failed assertion

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1385] opened 2016-06-22 12:46 UTC
From @klannon:

```
setparrot: pfs_table.cc:159[HEAD:4883ebaf]: Assertion 'fd == rfd || ((0 <= rfd && rfd < pointer_count) && pointers[rfd] == __null)' failed.
2016/06/22 04:26:16.31 parrot_run[78676] <child:82259> notice: received signal 6 (Aborted), killing all my children...
Could not open '/dev/tty' for immediate error reporting.
2016/06/22 04:26:16.31 parrot_run[78676] <child:82259> notice: sending myself 6 (Aborted), goodbye!
```

@dthain? @trshaffer

**Comment by btovar** [comment] 2016-06-22 12:57
Example of such failue: Task 10001

http://www.crc.nd.edu/~klannon/lobster/bdtreco_v0/processing/

**Comment by dthain** [comment] 2016-06-22 13:46
Well, I learned a new software engineering lesson today.
We should be making multiple assertions on independent properties, so we can see which one failed.
I'm going to make a pull with a more detailed failure message, and then let's see what's going on.

**Comment by klannon** [comment] 2016-06-22 13:52
If it helps you, I'd be really surprised if this is actually a Parrot bug.  This run went along great for 10 hours and then suddenly started having serious issues (see below).  I suspect something else is wrong and this is the symptom.  I don't suppose you have any guesses as to what could cause this as a symptom?

![all-tasks-hist](https://cloud.githubusercontent.com/assets/5149849/16269097/3dadd06a-3891-11e6-9d6c-1a6b0befaf1a.png)

**Comment by dthain** [comment] 2016-06-22 14:06
@btovar can you take it from here to get them running with the new version?

**Comment by dthain** [comment] 2016-06-22 14:06
Once we have some more info, I may be able to diagnose parrot further.

**Comment by btovar** [comment] 2016-06-22 14:23
will do

**Comment by btovar** [comment] 2016-06-22 14:38
Version ready on cctools-114-24ac5609-cvmfs-40cf5bba

**Comment by batrick** [comment] 2016-06-29 23:42
As the surrounding comment says, this assertion is caused by parrot's fd table getting out of sync with the kernel. One of the easiest ways to debug this is to enable this debug output:

https://github.com/cooperative-computing-lab/cctools/blob/b67c0379d32abba6af775adc6e7653a50c101ef6/parrot/src/pfs_dispatch64.cc#L978-L998

Then look at syscalls in the thread(s) which create new file descriptors (accept, open, pipe, socket, etc.).

If you can share a debug log with `-dall` and/or a way to reproduce it, I'll take a look when I have some time.

**Comment by dthain** [comment] 2016-08-25 15:42
Are we still seeing this problem, or did it go away?

**Comment by klannon** [comment] 2016-08-25 16:06
We have not seen it since you implemented the code to help debug it.  Sorry.

**Comment by dthain** [comment] 2016-11-08 16:19
Ok, I'm going to classify this one as "cosmic ray shower" and close it.
Bug us again if necessary...

**Closed by dthain** 2016-11-08 16:19 UTC
Labels: bug, critical, Parrot
