### ISSUE TITLE
Makeflow Local resource ignored

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1439] opened 2016-08-19 18:06 UTC
After getting a question from @hmeng-19 about the expected behavior of Makeflow -T local, I found out through some testing that we no longer use resource specifications for scheduling local jobs. Currently we run one job per core regardless of the core specification, and completely ignore memory and disk. Just wanted to discuss how we should handle/fix this. @btovar @dthain

**Comment by dthain** [comment] 2016-08-19 18:12
This is a long-standing issue, see #254
It's not terribly hard to solve, we just need to keep a count as we dispatch jobs.

**Comment by nhazekam** [comment] 2016-08-19 18:17
Thanks for pointing to this. I had forgotten about this previous issue.

**Comment by dthain** [comment] 2016-12-06 21:35
Closing as duplicate of #254

**Closed by dthain** 2016-12-06 21:35 UTC
Labels: bug, Makeflow
